/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'matt' at '23/09/17 11:35 AM' with Gradle 2.14.1
 *
 * @author matt, @date 23/09/17 11:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
